# Alternative GNU Make workspace makefile autogenerated by Premake

ifndef config
  config=debug
endif

ifndef verbose
  SILENT = @
endif

ifeq ($(config),debug)
  Internship_config = debug

else ifeq ($(config),release)
  Internship_config = release

else
  $(error "invalid configuration $(config)")
endif

PROJECTS := Internship

.PHONY: all clean help $(PROJECTS) 

all: $(PROJECTS)

Internship:
ifneq (,$(Internship_config))
	@echo "==== Building Internship ($(Internship_config)) ===="
	@${MAKE} --no-print-directory -C . -f Internship.make config=$(Internship_config)
endif

clean:
	@${MAKE} --no-print-directory -C . -f Internship.make clean

help:
	@echo "Usage: make [config=name] [target]"
	@echo ""
	@echo "CONFIGURATIONS:"
	@echo "  debug"
	@echo "  release"
	@echo ""
	@echo "TARGETS:"
	@echo "   all (default)"
	@echo "   clean"
	@echo "   Internship"
	@echo ""
	@echo "For more information, see https://github.com/premake/premake-core/wiki"